target: all,alertmanager

auth_enabled: true

limits:
  accept_ha_samples: true

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: consul
      consul:
        host: consul:8500
      
ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  lifecycler:
    # We want to start immediately.
    join_after: 0
    final_sleep: 0s
    num_tokens: 512
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3

memberlist:
  join_members: [cortex-1, cortex-2, cortex-3]

querier:
  query_ingesters_within: 3h
  at_modifier_enabled: true

store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 3
    kvstore:
      store: memberlist

blocks_storage:
  backend: s3
  tsdb:
    dir: /data/cortex-tsdb-ingester
    ship_interval: 1m
    block_ranges_period: [ 2h ]
    retention_period: 3h

  bucket_store:
    sync_dir: /data/cortex-tsdb-querier

  s3:
    endpoint:          minio:9000
    bucket_name:       cortex
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure:          true

ruler:
  enable_api: true
  enable_sharding: true
  poll_interval: 2s
  ring:
    kvstore:
      store: memberlist
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1/alertmanager

ruler_storage:
  backend: s3
  s3:
    bucket_name:       cortex
    endpoint:          minio:9000
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure: true

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /cortex/config/alertmanager-fallback-config.yaml
  external_url: http://localhost:8080/alertmanager
  sharding_enabled: true
  sharding_ring:
    kvstore:
      store: memberlist
  enable_api: true

alertmanager_storage:
  backend: s3
  s3:
    bucket_name:       cortex
    endpoint:          minio:9000
    access_key_id:     cortex
    secret_access_key: supersecret
    insecure: true

runtime_config:
  file: /cortex/config/runtime.yaml
