http:
  port: 6666
cortex: http://load-balancer
s3:
  bucket:            cortex
  endpoint:          minio:9000
  access_key_id:     cortex
  access_key_secret: supersecret
  secure: false
windows: /etc/cortex-slo/windows/*.yaml