global:
  scrape_interval: 15s
  external_labels:
    cluster: demo
    namespace: demo
    __replica__: ${PODNAME} 

scrape_configs:
  - job_name: demo/cortex
    static_configs:
      - targets: ['cortex-1','cortex-2','cortex-3']

  - job_name: myservice
    static_configs:
      - targets: ['myservice:8080']

remote_write:
  - url: http://load-balancer/api/v1/push
    headers:
      X-Scope-OrgID: demo
    send_exemplars: true